# Generated by Django 4.1 on 2022-08-14 07:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Locker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=50)),
                ('start_time', models.IntegerField(default=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)])),
                ('end_time', models.IntegerField(default=22, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(24)])),
                ('price', models.IntegerField(default=4000, help_text='무인 사물함의 기본가격을 적어주세요!', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)])),
                ('image', models.ImageField(upload_to='lockers')),
            ],
        ),
    ]
