# Generated by Django 4.1 on 2022-08-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='image',
            field=models.ImageField(upload_to='lockers/'),
        ),
    ]
