# Generated by Django 4.1 on 2022-08-14 07:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0002_alter_locker_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locker',
            name='end_time',
            field=models.SmallIntegerField(default=22, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AlterField(
            model_name='locker',
            name='price',
            field=models.SmallIntegerField(default=4000, help_text='무인 사물함의 기본가격을 적어주세요!', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='locker',
            name='start_time',
            field=models.SmallIntegerField(default=9, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
