# Generated by Django 4.1 on 2022-08-15 00:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0005_alter_locker_latitude_alter_locker_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locker',
            name='price',
        ),
        migrations.AddField(
            model_name='locker',
            name='big_price',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locker',
            name='mid_price',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locker',
            name='small_price',
            field=models.SmallIntegerField(default=2000, help_text='무인 사물함의 기본가격을 적어주세요!', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100000)]),
        ),
        migrations.AlterField(
            model_name='locker',
            name='image',
            field=models.ImageField(default='default.png', upload_to='lockers/'),
        ),
    ]
