# Generated by Django 4.1 on 2022-08-17 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0006_remove_locker_price_locker_big_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeMo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('password', models.CharField(max_length=30)),
                ('usage_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locker', to='locker.locker')),
            ],
        ),
    ]
